import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Landing from '../components/Landing'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Online Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" /> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" /> */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&family=Mulish:wght@300;400;500;600;700&display=swap" rel="stylesheet" /> */}
      </Head>

      <main>
        <Landing />
      </main>
    </div>
  )
}
